// <auto-generated />
using System;
using ComprarProgramada.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ComprarProgramada.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ComprarProgramada.Domain.Entities.CestaItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CestaTopFiveId")
                        .HasColumnType("int");

                    b.Property<decimal>("Percentual")
                        .HasColumnType("decimal(6,3)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("CestaTopFiveId", "Ticker")
                        .IsUnique();

                    b.ToTable("CestaItens", (string)null);
                });

            modelBuilder.Entity("ComprarProgramada.Domain.Entities.CestaTopFive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataDesativacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Ativa");

                    b.ToTable("CestasTopFive", (string)null);
                });

            modelBuilder.Entity("ComprarProgramada.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.Property<DateTime>("DataAdesao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataSaida")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("ValorMensal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("ComprarProgramada.Domain.Entities.ContaFilhote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NumeroConta")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId")
                        .IsUnique();

                    b.HasIndex("NumeroConta")
                        .IsUnique();

                    b.ToTable("ContasFilhote", (string)null);
                });

            modelBuilder.Entity("ComprarProgramada.Domain.Entities.ContaMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NumeroConta")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("NumeroConta")
                        .IsUnique();

                    b.ToTable("ContasMaster", (string)null);
                });

            modelBuilder.Entity("ComprarProgramada.Domain.Entities.CustodiaFilhote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContaFilhoteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContaFilhoteId")
                        .IsUnique();

                    b.ToTable("CustodiasFilhote", (string)null);
                });

            modelBuilder.Entity("ComprarProgramada.Domain.Entities.CustodiaFilhoteItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustodiaFilhoteId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecoMedio")
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("CustodiaFilhoteId", "Ticker")
                        .IsUnique();

                    b.ToTable("CustodiasFilhoteItens", (string)null);
                });

            modelBuilder.Entity("ComprarProgramada.Domain.Entities.CustodiaMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContaMasterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContaMasterId")
                        .IsUnique();

                    b.ToTable("CustodiasMaster", (string)null);
                });

            modelBuilder.Entity("ComprarProgramada.Domain.Entities.CustodiaMasterItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustodiaMasterId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecoMedio")
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("CustodiaMasterId", "Ticker")
                        .IsUnique();

                    b.ToTable("CustodiasMasterItens", (string)null);
                });

            modelBuilder.Entity("ComprarProgramada.Domain.Entities.Distribuicao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<int>("ContaFilhoteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<DateOnly>("DataDistribuicao")
                        .HasColumnType("date");

                    b.Property<int>("OrdemCompraId")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorAporte")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorTotalIrDedoDuro")
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("OrdemCompraId", "ClienteId")
                        .IsUnique();

                    b.ToTable("Distribuicoes", (string)null);
                });

            modelBuilder.Entity("ComprarProgramada.Domain.Entities.DistribuicaoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DistribuicaoId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<decimal>("ValorIrDedoDuro")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("ValorOperacao")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DistribuicaoId");

                    b.ToTable("DistribuicaoItens", (string)null);
                });

            modelBuilder.Entity("ComprarProgramada.Domain.Entities.OrdemCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CestaTopFiveId")
                        .HasColumnType("int");

                    b.Property<int>("ContaMasterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<DateOnly>("DataCompra")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorTotalConsolidado")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CestaTopFiveId");

                    b.HasIndex("ContaMasterId");

                    b.HasIndex("DataCompra")
                        .IsUnique();

                    b.ToTable("OrdensCompra", (string)null);
                });

            modelBuilder.Entity("ComprarProgramada.Domain.Entities.OrdemCompraItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrdemCompraId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("QuantidadeFracionario")
                        .HasColumnType("int");

                    b.Property<int>("QuantidadeLotePadrao")
                        .HasColumnType("int");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("OrdemCompraId", "Ticker")
                        .IsUnique();

                    b.ToTable("OrdensCompraItens", (string)null);
                });

            modelBuilder.Entity("ComprarProgramada.Domain.Entities.CestaItem", b =>
                {
                    b.HasOne("ComprarProgramada.Domain.Entities.CestaTopFive", null)
                        .WithMany("Itens")
                        .HasForeignKey("CestaTopFiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ComprarProgramada.Domain.Entities.ContaFilhote", b =>
                {
                    b.HasOne("ComprarProgramada.Domain.Entities.Cliente", "Cliente")
                        .WithOne("ContaFilhote")
                        .HasForeignKey("ComprarProgramada.Domain.Entities.ContaFilhote", "ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("ComprarProgramada.Domain.Entities.CustodiaFilhote", b =>
                {
                    b.HasOne("ComprarProgramada.Domain.Entities.ContaFilhote", "ContaFilhote")
                        .WithOne("Custodia")
                        .HasForeignKey("ComprarProgramada.Domain.Entities.CustodiaFilhote", "ContaFilhoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContaFilhote");
                });

            modelBuilder.Entity("ComprarProgramada.Domain.Entities.CustodiaFilhoteItem", b =>
                {
                    b.HasOne("ComprarProgramada.Domain.Entities.CustodiaFilhote", null)
                        .WithMany("Itens")
                        .HasForeignKey("CustodiaFilhoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ComprarProgramada.Domain.Entities.CustodiaMaster", b =>
                {
                    b.HasOne("ComprarProgramada.Domain.Entities.ContaMaster", "ContaMaster")
                        .WithOne("Custodia")
                        .HasForeignKey("ComprarProgramada.Domain.Entities.CustodiaMaster", "ContaMasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContaMaster");
                });

            modelBuilder.Entity("ComprarProgramada.Domain.Entities.CustodiaMasterItem", b =>
                {
                    b.HasOne("ComprarProgramada.Domain.Entities.CustodiaMaster", null)
                        .WithMany("Itens")
                        .HasForeignKey("CustodiaMasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ComprarProgramada.Domain.Entities.Distribuicao", b =>
                {
                    b.HasOne("ComprarProgramada.Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ComprarProgramada.Domain.Entities.OrdemCompra", "OrdemCompra")
                        .WithMany()
                        .HasForeignKey("OrdemCompraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("OrdemCompra");
                });

            modelBuilder.Entity("ComprarProgramada.Domain.Entities.DistribuicaoItem", b =>
                {
                    b.HasOne("ComprarProgramada.Domain.Entities.Distribuicao", null)
                        .WithMany("Itens")
                        .HasForeignKey("DistribuicaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ComprarProgramada.Domain.Entities.OrdemCompra", b =>
                {
                    b.HasOne("ComprarProgramada.Domain.Entities.CestaTopFive", "CestaTopFive")
                        .WithMany()
                        .HasForeignKey("CestaTopFiveId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ComprarProgramada.Domain.Entities.ContaMaster", "ContaMaster")
                        .WithMany()
                        .HasForeignKey("ContaMasterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CestaTopFive");

                    b.Navigation("ContaMaster");
                });

            modelBuilder.Entity("ComprarProgramada.Domain.Entities.OrdemCompraItem", b =>
                {
                    b.HasOne("ComprarProgramada.Domain.Entities.OrdemCompra", null)
                        .WithMany("Itens")
                        .HasForeignKey("OrdemCompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ComprarProgramada.Domain.Entities.CestaTopFive", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("ComprarProgramada.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("ContaFilhote");
                });

            modelBuilder.Entity("ComprarProgramada.Domain.Entities.ContaFilhote", b =>
                {
                    b.Navigation("Custodia");
                });

            modelBuilder.Entity("ComprarProgramada.Domain.Entities.ContaMaster", b =>
                {
                    b.Navigation("Custodia");
                });

            modelBuilder.Entity("ComprarProgramada.Domain.Entities.CustodiaFilhote", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("ComprarProgramada.Domain.Entities.CustodiaMaster", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("ComprarProgramada.Domain.Entities.Distribuicao", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("ComprarProgramada.Domain.Entities.OrdemCompra", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
